// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfgwgyhzhmopyngyaogo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmZ3dneWh6aG1vcHluZ3lhb2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjg5NTIsImV4cCI6MjA2Mzg0NDk1Mn0.9RiQaEmaD79UX3Q8fSvLktULhKD6CeH4zEklUyix8y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);